server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ASUSJI/Desktop/practice/git-local-repo
          default-label: master


