server:
  port: 0

spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
      name: ecomerce


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: 'create-drop'


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    web:
      exposure:
        include: refresh, health, beans  # refresh는 post로 보내야 하는데 보내면 빌드안해도 외부 yml를 가져올수있다.

greeting:
  message: Welcome to the Simple E-commerce.